openapi: 3.0.0
info:
  title: 'Have I been pwned?'
  version: 1.0.0
paths:
  /breachedaccount/{account}:
    get:
      description: The most common use of the API is to return a list of all breaches
        a particular account has been involved in. The API takes a single parameter
        which is the account to be searched for. The account is not case sensitive
        and will be trimmed of leading or trailing white spaces. The account should
        always be URL encoded.
      parameters:
      - description: Account to be checked against the 'Have I been pwned API'
        in: path
        name: account
        content:
          application/x-www-form-urlencoded:
            schema:
              type: string
      responses:

        '404':
          description: Not found
          schema: {}
        '200':
          description: List all breached sites
          schema: array
        default:
          description: Error
          schema: {}
  /breaches:
    get:
      description: List all breached sites that are currently available in the Have I Been Pwned API
      parameters: []
      responses:
        default:
          description: List all breached sites that are currently available in the Have I Been Pwned API.
          schema: {}
      summary: Get all breached sites        
servers:
- url: https://haveibeenpwned.com/api/v3
