openapi: 3.0.0
info:
  title: 'Have I been pwned?'
  version: 1.0.0
paths:
  /breachedaccount/{account}:
    get:
      description: The most common use of the API is to return a list of all breaches
        a particular account has been involved in. The API takes a single parameter
        which is the account to be searched for. The account is not case sensitive
        and will be trimmed of leading or trailing white spaces. The account should
        always be URL encoded.
      parameters:
      - description: Account to be checked against the 'Have I been pwned API'
        in: path
        name: account
        required: true
        schema:
          type: string
        style: form
      responses:
        default:
          description: default
          schema: {}
      summary: Get all breaches for an account
servers:
- url: https://haveibeenpwned.com/api/v3
